version: '3.3'
services:
<<<<<<< HEAD
=======

>>>>>>> master
  dts-rmp:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VUE_APP_CONNECTION_STRING: ${VUE_APP_CONNECTION_STRING}
        VUE_APP_RMP_DB_PASSWORD: ${VUE_APP_RMP_DB_PASSWORD}
    container_name: dts-rmp
    restart: always
    ports:
      - '80:3000'

  e2e:
    build:
      context: ./
      dockerfile: Cypress.Dockerfile
    container_name: cypress
    depends_on:
      - dts-rmp
    environment:
      - CYPRESS_baseUrl=http://localhost
    restart: always
    network_mode: 'host'
    volumes:
      - './cypress/reports:/cypress/report'
