FROM node:lts-alpine
WORKDIR /home/dts-rmp
COPY package*.json ./
RUN npm i
COPY . .
RUN npm run build
ARG VUE_APP_CONNECTION_STRING=placeholder
ENV VUE_APP_CONNECTION_STRING=${VUE_APP_CONNECTION_STRING}
ARG VUE_APP_RMP_DB_PASSWORD=placeholder
ENV VUE_APP_RMP_DB_PASSWORD=${VUE_APP_RMP_DB_PASSWORD}
ARG VUE_APP_JWT_SECRET=placeholder
ENV VUE_APP_JWT_SECRET=${VUE_APP_JWT_SECRET}
ARG baseURL=placeholder
ENV baseURL=${baseURL}
EXPOSE ${NUXT_PORT}
CMD [ "npm", "start" ]
