FROM node:lts-alpine
WORKDIR /home/dts-rmp
COPY package*.json ./
RUN npm i
COPY . .
RUN npm run build
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ARG VUE_APP_CONNECTION_STRING=placeholder
ENV VUE_APP_CONNECTION_STRING=${VUE_APP_CONNECTION_STRING}
ARG VUE_APP_RMP_DB_PASSWORD=placeholder
ENV VUE_APP_RMP_DB_PASSWORD=${VUE_APP_RMP_DB_PASSWORD}
ARG VUE_APP_JWT_SECRET=placeholder
ENV VUE_APP_JWT_SECRET=${VUE_APP_JWT_SECRET}
ARG baseUrl=placeholder
ENV baseUrl=${baseUrl}
EXPOSE ${NUXT_PORT}
CMD [ "npm", "start" ]
