name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v1

      - name: Generate build number
        uses: einaregilsson/build-number@v1
        with:
          token: ${{secrets.github_token}}
      - uses: azure/docker-login@v1
        with:
          login-server: mtscontainers.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: docker build and push client server
        run: |
          docker build --build-arg DB_NAME=temp -t mtscontainers.azurecr.io/dts-rmp:latest .
          docker tag mtscontainers.azurecr.io/dts-rmp:latest mtscontainers.azurecr.io/dts-rmp:$BUILD_NUMBER
          docker push mtscontainers.azurecr.io/dts-rmp:latest
          docker push mtscontainers.azurecr.io/dts-rmp:$BUILD_NUMBER
      - name: jenkins client server deployment job
        uses: wei/curl@v1
        with:
          args: -X POST https://jenkins.dts-stn.com/job/rmp/buildWithParameters?docker_tag=$BUILD_NUMBER --user jenkinsbot:${{ secrets.JENKINS_SP_TOKEN }}

