name: Build and Publish Staging

on:
  push:
    branches:
      - main

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v1

      - name: Generate build number
        uses: einaregilsson/build-number@v1
        with:
          token: ${{secrets.github_token}}
      - uses: azure/docker-login@v1
        with:
          login-server: mtscontainers.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: docker build and push client server
        run: |
          docker build --build-arg DB_NAME=temp -t mtscontainers.azurecr.io/dts-rmp:latest .
          docker tag mtscontainers.azurecr.io/dts-rmp:latest mtscontainers.azurecr.io/dts-rmp:$BUILD_NUMBER
          docker push mtscontainers.azurecr.io/dts-rmp:latest
          docker push mtscontainers.azurecr.io/dts-rmp:$BUILD_NUMBER
      
      - name: 'Deploy Staging (migration test)'
        uses: stigmelling/jenkins-action@v1.1
        env: 
          buildnum: $BUILD_NUMBER
        with:
         jenkinsUrl: 'https://jenkins.dev.dts-stn.com'
         username: 'dtsrobot'
         token: '${{ secrets.DTSROBOT_API_TOKEN }}'
         job: 'deploy_rmp'
         params: '{"DOCKER_TAG": "${{ env.buildnum }}", "TIER": "frontend", "TARGET": "dev"}'
